CREATE ALGORITHM=UNDEFINED DEFINER=`amritanair`@`%` SQL SECURITY DEFINER VIEW `cs5200_fall2018_A2_amritanair`.`developer_details` AS (select `p`.`p_id` AS `developer_id`,`p`.`first_name` AS `first_name`,`p`.`last_name` AS `last_name`,`p`.`user_name` AS `user_name`,`p`.`email` AS `email` from (`cs5200_fall2018_A2_amritanair`.`person` `p` join `cs5200_fall2018_A2_amritanair`.`developer` `d`) where (`p`.`p_id` = `d`.`p_id`));

CREATE ALGORITHM=UNDEFINED DEFINER=`amritanair`@`%` SQL SECURITY DEFINER VIEW `cs5200_fall2018_A2_amritanair`.`page_privilege_role` AS select `pp`.`page_id` AS `page_id`,`pp`.`privilege` AS `privilege`,`pp`.`developer_id` AS `developer_id`,`pr`.`role` AS `role` from (`cs5200_fall2018_A2_amritanair`.`page_privilege` `pp` join `cs5200_fall2018_A2_amritanair`.`page_role` `pr`) where ((`pp`.`page_id` = `pr`.`page_id`) and (`pp`.`developer_id` = `pr`.`developer_id`));


CREATE ALGORITHM=UNDEFINED DEFINER=`amritanair`@`%` SQL SECURITY DEFINER VIEW `cs5200_fall2018_A2_amritanair`.`dev_website_role_privilege` AS select `wr`.`developer_id` AS `dev_id`,`wr`.`website_id` AS `website_id`,`wr`.`role_name` AS `role_name`,`wp`.`privilege_name` AS `privilege_name` from (`cs5200_fall2018_A2_amritanair`.`website_role` `wr` join `cs5200_fall2018_A2_amritanair`.`website_privilege` `wp`) where ((`wr`.`website_id` = `wp`.`website_id`) and (`wp`.`developer_id` = `wr`.`developer_id`));

CREATE ALGORITHM=UNDEFINED DEFINER=`amritanair`@`%` SQL SECURITY DEFINER VIEW `cs5200_fall2018_A2_amritanair`.`website_details_view` AS select `w`.`website_name` AS `website_name`,`w`.`visits` AS `visits`,`w`.`updated` AS `website_updated`,`v`.`dev_id` AS `dev_id`,`v`.`website_id` AS `website_id`,`v`.`role_name` AS `role_name`,`v`.`privilege_name` AS `privilege_name` from (`cs5200_fall2018_A2_amritanair`.`website` `w` join `cs5200_fall2018_A2_amritanair`.`dev_website_role_privilege` `v` on((`w`.`website_id` = `v`.`website_id`)));


CREATE ALGORITHM=UNDEFINED DEFINER=`amritanair`@`%` SQL SECURITY DEFINER VIEW `cs5200_fall2018_A2_amritanair`.`page_details_view` AS select `p`.`title` AS `title`,`p`.`website_id` AS `website_id`,`p`.`views` AS `views`,`p`.`updated` AS `updated`,`v`.`role` AS `role`,`v`.`privilege` AS `privilege`,`v`.`developer_id` AS `developer_id`,`v`.`page_id` AS `page_id` from (`cs5200_fall2018_A2_amritanair`.`page` `p` join `cs5200_fall2018_A2_amritanair`.`page_privilege_role` `v`) where (`p`.`page_id` = `v`.`page_id`);

CREATE ALGORITHM=UNDEFINED DEFINER=`amritanair`@`%` SQL SECURITY DEFINER VIEW `cs5200_fall2018_A2_amritanair`.`merged_page_website_view` AS select `pd`.`developer_id` AS `developer_id`,`wd`.`website_name` AS `website_name`,`wd`.`visits` AS `visits`,`wd`.`website_updated` AS `website_updated`,`wd`.`role_name` AS `website_role_name`,`wd`.`privilege_name` AS `website_privilege_name`,`pd`.`title` AS `title`,`pd`.`views` AS `views`,`pd`.`updated` AS `updated`,`pd`.`role` AS `page_role_name`,`pd`.`privilege` AS `page_privilege_name` from (`cs5200_fall2018_A2_amritanair`.`website_details_view` `wd` join `cs5200_fall2018_A2_amritanair`.`page_details_view` `pd`) where ((`wd`.`website_id` = `pd`.`website_id`) and (`wd`.`dev_id` = `pd`.`developer_id`));

CREATE ALGORITHM=UNDEFINED DEFINER=`amritanair`@`%` SQL SECURITY DEFINER VIEW `cs5200_fall2018_A2_amritanair`.`deleveloper_roles_and_privileges` AS select `d`.`first_name` AS `first_name`,`d`.`last_name` AS `last_name`,`d`.`user_name` AS `user_name`,`d`.`email` AS `email`,`wp`.`website_name` AS `website_name`,`wp`.`visits` AS `visits`,`wp`.`website_updated` AS `website_updated`,`wp`.`website_role_name` AS `website_role_name`,`wp`.`website_privilege_name` AS `website_privilege_name`,`wp`.`title` AS `title`,`wp`.`views` AS `views`,`wp`.`updated` AS `updated`,`wp`.`page_role_name` AS `page_role_name`,`wp`.`page_privilege_name` AS `page_privilege_name` from (`cs5200_fall2018_A2_amritanair`.`developer_details` `d` join `cs5200_fall2018_A2_amritanair`.`merged_page_website_view` `wp`) where (`d`.`developer_id` = `wp`.`developer_id`);

select * from deleveloper_roles_and_privileges;
